### ISSUE TITLE
各阶段所需的辅导

### ISSUE THREAD

**Issue by hyg** [P2Club/P2Club#14]
根据[成长为规则设计者的过程和自检方法](https://github.com/P2Club/P2Club/issues/6) ，成长过程要经历：
1、局部规则整理
2、局部规则改进
3、全局规则整理
4、全局规则改进
5、全局规则创新
五个阶段。

你认为这五个阶段分别需要哪些辅导？

**Comment by hyg** [comment]
1、局部规则整理：
    1. 识别真正实行的规则，剔除没有实际效力的面上规则。
    2. 理清边界，提炼和外界的接口。
2、局部规则改进：
    1. 认识贡献分布的量化和变化。
    2. 初步了解利益分配的常用套路。
3、全局规则整理：
    1. 补充其它部门的业务知识，认识跨部门的贡献分布的量化和变化。
    2. 认识核心职权，以及合理的行使要求。
4、全局规则改进：
    1. 约束核心职权。
    2. 掌握层次化的利益分配套路。
5、全局规则创新：
    1. 去除核心职权。
    2. 设立内部记账单位。
    3. 内部成员、外部合作者、客户的统一。

**Comment by Zhongfang** [comment]
1、局部规则整理：
1.0. 认识”局部“之整体，分析局部之组织构架，内部协作机制；
